#!/usr/bin/env node
// Build the web test build: the engine compiled to WebAssembly (crates/web),
// the demo vault it opens, and the UI in `web` mode, into `dist-web/`.
//
// Runs locally and on Vercel (vercel.json). Anything missing is fetched into
// `target/`: the wasm32-wasip1 Rust target, and wasi-sdk, whose clang and libc
// compile the SQLite bundled into the engine. On a machine with no Rust at all
// (Vercel) rustup is installed first.
//
//   node scripts/build-web.mjs            build everything
//   node scripts/build-web.mjs --engine   engine + vault only (for `vite --mode web`)

import { execSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "target", "web");
const WASI_SDK = "25";
const TARGET = "wasm32-wasip1";

const run = (cmd, env = {}) => execSync(cmd, { cwd: root, stdio: "inherit", env: { ...process.env, ...env } });
const has = (cmd) => {
  try {
    execSync(`${cmd} --version`, { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
};

function ensureRust() {
  const cargoBin = path.join(os.homedir(), ".cargo", "bin");
  process.env.PATH = `${cargoBin}${path.delimiter}${process.env.PATH}`;
  if (!has("cargo")) {
    console.log("[build-web] installing Rust");
    run("curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal");
  }
  if (has("rustup")) run(`rustup target add ${TARGET}`);
}

function ensureWasiSdk() {
  if (process.env.WASI_SDK_PATH) return process.env.WASI_SDK_PATH;
  const arch = process.arch === "arm64" ? "arm64" : "x86_64";
  const platform = { linux: "linux", darwin: "macos" }[process.platform];
  if (!platform) throw new Error("set WASI_SDK_PATH: no prebuilt wasi-sdk for " + process.platform);
  const name = `wasi-sdk-${WASI_SDK}.0-${arch}-${platform}`;
  const dir = path.join(root, "target", name);
  if (!fs.existsSync(dir)) {
    console.log(`[build-web] fetching ${name}`);
    const url = `https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_SDK}/${name}.tar.gz`;
    fs.mkdirSync(path.dirname(dir), { recursive: true });
    run(`curl -sSfL "${url}" | tar xz -C "${path.dirname(dir)}"`);
  }
  return dir;
}

function buildEngine() {
  ensureRust();
  const sdk = ensureWasiSdk();
  run(`cargo build --release -p web --target ${TARGET}`, {
    CC_wasm32_wasip1: path.join(sdk, "bin", "clang"),
    AR_wasm32_wasip1: path.join(sdk, "bin", "llvm-ar"),
    CFLAGS_wasm32_wasip1: `--sysroot=${path.join(sdk, "share", "wasi-sysroot")}`,
    // WASI has no threads, and the page loads no SQLite extensions.
    LIBSQLITE3_FLAGS: "-DSQLITE_THREADSAFE=0 -DSQLITE_OMIT_LOAD_EXTENSION",
  });
  fs.mkdirSync(out, { recursive: true });
  fs.copyFileSync(path.join(root, "target", TARGET, "release", "web.wasm"), path.join(out, "synesis.wasm"));
}

// The demo vault as one JSON file the page unpacks into its in-memory
// filesystem. Text stays text; anything else travels as base64.
function bundleVault() {
  const base = path.join(root, "examples", "demo-vault");
  // Generated by the app, and ignored by git for the same reason.
  const skip = new Set([".bible-study/sync", "Scripture"]);
  const files = {};
  const walk = (rel) => {
    for (const e of fs.readdirSync(path.join(base, rel), { withFileTypes: true })) {
      const r = rel ? `${rel}/${e.name}` : e.name;
      if (skip.has(r)) continue;
      if (e.isDirectory()) walk(r);
      else {
        const bytes = fs.readFileSync(path.join(base, r));
        const text = /\.(md|json|canvas)$/.test(r);
        files[r] = text ? { text: bytes.toString("utf8") } : { base64: bytes.toString("base64") };
      }
    }
  };
  walk("");
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, "demo-vault.json"), JSON.stringify(files));
}

buildEngine();
bundleVault();
if (!process.argv.includes("--engine")) run("npx vite build --mode web");
